spring:
  profiles:
    default: local

---

logging:
  level:
    sql: debug
    web: debug
spring:
  config:
    activate:
      on-profile: local

  application:
    name: nunutalk
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/nunutalk
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /api-test # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    groups-order: DESC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
    paths-to-match:
      - /api/** # swagger-ui에 표시할 api의 엔드포인트 패턴
---

spring:
  config:
    activate:
      on-profile: test

  application:
    name: nunutalk
  datasource:
    url: jdbc:h2:mem:db
    username: minwoo
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100