spring:
  profiles:
    default: local

---

logging:
  level:
    sql: debug
    web: debug
spring:
  config:
    activate:
      on-profile: local

  application:
    name: nunutalk
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/nunutalk
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  config:
    activate:
      on-profile: test

  application:
    name: nunutalk
  datasource:
    url: jdbc:h2:mem:db
    username: minwoo
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100